### ISSUE TITLE
Updates for llvm-15 and llvm-16?

### ISSUE THREAD

**Issue by hjudt** [rpav/c2ffi#114]
Any chance of updates (aka branches/releases) for llvm-15 and llvm-16?

There are [build fixes](https://github.com/rpav/c2ffi/issues/110) for llvm-15, would it be possible to create a branch with this fix? I am a package maintainer and keeping up this organizational ado would make it less cumbersome having to deal with the updates.

**Comment by rpav** [comment]
Right! I'll try and get this out this weekend.

**Comment by rpav** [comment]
Like two weeks later but I have actually not forgotten about this, just not quite gotten there.

**Comment by rpav** [comment]
I finally got everything in order and have started work for clang-15; in terms of building, it mostly looks like they changed init options around a bit.  It's hard to tell yet if this is the only major change.

**Comment by hjudt** [comment]
Ok, thanks a lot for working on this!

**Comment by hjudt** [comment]
Hi! Any updates on this?

**Comment by rpav** [comment]
Yeah finally have a preliminary and apparently-working llvm-15 version.

Ditched NixOS for versioning and am currently working on an alpine-based container build that will hopefully be an "offically-supported" way to build and run c2ffi with arbitrary versions of llvm/clang, but need to minimize some user complexity.  Hopefully once this works clang-16 should be next.

**Comment by hjudt** [comment]
Thank you very much for your work on llvm-15, it worked and compiled fine and I was able to provide an updated version in the gentoo portage tree.

Are you still working on an updated llvm-16 version? In gentoo, version 16 has already been stabilized which means older versions will be deprecated and removed in a few weeks/months, so it would be nice to have updates rather sooner than later...

**Comment by hjudt** [comment]
hi! any updates for llvm-16?

**Comment by rpav** [comment]
Life has been dumb but hopefully soon.

**Comment by hjudt** [comment]
Any news? llvm-17 has already arrived...

**Comment by rpav** [comment]
This is updated for llvm-16 .. it didn't even require changes other than bumping the required version. :P It would be helpful for people using it to try / post an error log.

llvm-17 doesn't appear to be officially here yet; I'll probably get to it when Arch or Alpine post packages.  If you're working on prerelease, also test to see there are even any changes required; there may not be once again.

**Comment by hjudt** [comment]
Thank you. llvm-16 builds fine here, so I can issue a pull request for it now in the gentoo repo.

llvm-17 is still unstable in the portage package repository, so that might still take some while to stabilize, but simply bumping the version to 17 gives me a compile error for AST.cpp, I'll open another issue for it and append the output there.
