### ISSUE TITLE
Make path to llvm-config configurable

### ISSUE THREAD

**Issue by rmattes** [rpav/c2ffi#16]
Currently, `configure` calls `llvm-config` assuming it can be found in `$PATH`.
This will fail with some Linux distributions that support multiple versions of llvm/clang
(Debian installs `llvm-config-3.n` for `n=0...6`).
It might be a good idea to extend  `configure.ac` with a `--with-llvm-config`switch to explicitly set the path of that script.

**Comment by rpav** [comment]
I'll be replacing autoconf with CMake stuff relatively soon, so this should hopefully be fixed.
