### ISSUE TITLE
Can't build.

### ISSUE THREAD

**Issue by BradWBeer** [rpav/c2ffi#17]
c2ffi.cpp:86:27: error: no viable conversion from 'std::unique_ptr<clang::ASTConsumer>' to                                                                                                    
      'clang::ASTConsumer *'                                                                                                                                                                  
        ci.setASTConsumer(std::unique_ptr<clang::ASTConsumer>(astc));

**Comment by rpav** [comment]
This looks like you're using an old version of clang (old versions used raw pointers, newer versions use `std::unique_ptr`).  Check the reported version and, more importantly, the svn revision by `clang -v`.  Older branches of c2ffi are available for earlier clang revisions; however there may be "intermediate" versions which don't build.

**Comment by BradWBeer** [comment]
That looks like it fixed it. Before I spend a lot of time on this, I'm trying to create bindings to the bullet physics library. It's C++, heavily so. Can I make cffi bindings to it?

**Comment by rpav** [comment]
You *can* in *theory*, but the reality is you need to write (or generate) a lot of glue for C++, and nothing does this for CL to my knowledge.  The C++ information from c2ffi is actually the hardest bit, and I've been meaning to add this to autowrap, but I haven't yet.

**Comment by kingcons** [comment]
@BradWBeer I managed to do this once using (IIRC verrazano) and seem to remember it going *fairly* smoothly but there's likely some bitrot by now: https://common-lisp.net/project/fetter/

**Comment by rpav** [comment]
This was resolved I believe (other than using it for bullet!).
