### ISSUE TITLE
default system include path list is not populated

### ISSUE THREAD

**Issue by attila-lendvai** [rpav/c2ffi#21]
AFAIU, when c2ffi invokes the LLVM C parser code through the LLVM API, then it needs to give a full list of include search paths. when using c2ffi with an LLVM that has not been installed into the default install-prefix, then the standard headers are not found (e.g. stdbool.h).

this seems to be a kludge in LLVM itself, but i open this issue to be able to track this.

see e.g. the FIXME comment in http://clang.llvm.org/doxygen/InitHeaderSearch_8cpp_source.html at line 351 (AddDefaultCPlusPlusIncludePaths).

**Comment by attila-lendvai** [comment]
see also: http://lists.llvm.org/pipermail/cfe-dev/2012-July/022893.html

**Comment by rpav** [comment]
I've tried using `clang::ApplyHeaderSearchOptions` which should, in theory, add some default paths, but it doesn't seem to do particularly much.  I actually *do* have a number of clang header locations hardcoded (as per the post), see `src/c2ffi.cpp` near the top of `main`.  If you have an installation path elsewhere, try specifying that as a `-I`.

**Comment by spaceotter** [comment]
Maybe this? https://github.com/rpav/c2ffi/pull/89

**Comment by rpav** [comment]
This seems resolved; let me know / reopen if there's actually a persistent issue.
