### ISSUE TITLE
clang 3.7

### ISSUE THREAD

**Issue by kvsari** [rpav/c2ffi#22]
Can't build. Error in Expr.cpp on line 187;

`../../src/Expr.cpp:187:49: error: member reference type 'const clang::Preprocessor::MacroState' is not a pointer; did you mean to use '.'?
        const clang::MacroInfo *mi = (*i).second->getMacroInfo();
                                     ~~~~~~~~~~~^~
                                                .
../../src/Expr.cpp:187:51: error: no member named 'getMacroInfo' in 'clang::Preprocessor::MacroState'
        const clang::MacroInfo *mi = (*i).second->getMacroInfo();`

Building on ArchLinux using clang-3.7.

**Comment by rpav** [comment]
Thanks.  I haven't had a chance to integrate 3.7 changes yet.  I hope to have that done today.

**Comment by rpav** [comment]
Err so definitely not going to be done today, possibly not for a few.  Will try to integrate the cmake stuff as well though.

**Comment by rpav** [comment]
This should be fixed.  Sorry for the delay.  Please reopen the ticket if there is an issue.
