### ISSUE TITLE
Backport to llvm-3.5?

### ISSUE THREAD

**Issue by mabragor** [rpav/c2ffi#23]
Hi, Ryan!

I'd really love to use C2FFI to make bindings for SDL2-GFX library.
However, I'm having a hard time building C2FFI.
The reason is, I'm on Debian Wheezy and it uses llvm-3.5 and clang-3.5 by default
-- hence I get plenty of build errors, at linking stage.

I've installed llvm-3.6 and clang-3.6 and even did update-alternatives, to make llvm-config
and clang point to 3.6 versions, however, I still get these build errors, apparently, I'm missing
some configuration.

So, do you know, what else needs to be done to properly use llvm 3.6 toolchain?
Either more update-alternatives commands (to make it default toolchain) or
some extra arguments to configure?

Or, perhaps, you could backport C2FFI to llvm 3.5 and clang 3.5 -- this way it should work
on Debian Wheezy out of the box?

I'm kind of frustrated now, because googling 'debian make llvm 3.6 the default' and the like
didn't give me any useful results...

Best regards,
Alex

**Comment by rpav** [comment]
Well, the llvm-3.5 branch *should* work with 3.5, and backporting what minor fixes/etc exist should be relatively easy.  (Of course I'm **already** like 2 versions behind though, given 3.8 is in the works...)

However I'd worry if the existing 3.5 branch doesn't compile.  Perhaps post the errors you're getting and let's see what's up.  Often (in my experience, *every single time*), the llvm/clang packages in a dist are poorly-built (if they're even the advertised version) and don't have all the requisite clang libs, and building your own is the only solution.

**Comment by mabragor** [comment]
I can't find llvm-3.5 branch in the list of branches in this repository.
Perhaps, it wasn't 'push -u' from your local machine?

**Comment by mabragor** [comment]
I.e., I see master, llvm-3.3 and llvm-3.4 branches.

**Comment by rpav** [comment]
Argh.  Fixed.

**Comment by mabragor** [comment]
Ok, llvm-3.5 didn't build with default debian clang and llvm -- trying to build clang and llvm from svn,
then will post, what happens.

**Comment by rpav** [comment]
If there are errors about anything in the long list of `CLANG_LIBS` in `src/Makefile.am`, that's the problem.  Really don't know why these aren't included.

**Comment by mabragor** [comment]
Eventually, I wasn't able to build an llvm + clang 3.5 release from subversion.
But the 3.6 release built just fine and then c2ffi, with this relase, as well.
So, closing, since my immediate problem (use c2ffi to generate bindings) is solved.

Thanks for the help! Perhaps, you may stress a hint to build llvm+clang from sources
(instead of taking the repo version) in bold
in README as, apparently, it is crucial to make things work.
