### ISSUE TITLE
LLVM configuration problem on El Capitan

### ISSUE THREAD

**Issue by marcoxa** [rpav/c2ffi#32]
Hi
I am trying to set up c2ffi on El Capitan.  I get the following configuration error:

`Spanakorizo:c2ffi marcoxa$ cd c2ffi/
Spanakorizo:c2ffi marcoxa$ mkdir build
Spanakorizo:c2ffi marcoxa$ cd build/
Spanakorizo:build marcoxa$ cmake ..
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:15 (find_package):
  Could not find a package configuration file provided by "LLVM" (requested
  version 3.7) with any of the following names:

```
LLVMConfig.cmake
llvm-config.cmake
```

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/Users/marcoxa/Projects/Software/c2ffi/c2ffi/build/CMakeFiles/CMakeOutput.log".
Spanakorizo:build marcoxa$ which llvm
Spanakorizo:build marcoxa$ 
`

Now.  What exactly should I do?  AFAIU my LLVM lives in
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

What am I missing?  Do I really really have to set up a separate LLVM installation on my machine?

Thanks

Marco

**Comment by rpav** [comment]
I don't know how or where Apple provides the LLVM "development" stuff, but you need that.  This should include not just `libclang.so`, but a bunch of other libraries such as `libclangAST.a` and similar.

**Comment by marcoxa** [comment]
Hi
`libclang.dylib` is on the system, but there is no trace of `libclangAST`.  Is it truly necessary?

MA

**Comment by rpav** [comment]
Those libraries are the core of what `c2ffi` (and clang itself, really) uses to parse.  I'm not sure if/how you can get the ones for the Xcode clang, but if you build your own (or use macports? haven't tested) you should have them.

**Comment by marcoxa** [comment]
Ok.  Downloaded le latest LLVM and just stashed it in my local account.
Only glitch, 3.7 is required, but 3.8 is what I've got.

So far it looks like it is working as advertised.

**Comment by rpav** [comment]
Ah yeah let me know if you have any issues, it should be fairly simple to update; I've just been focused on other things.

**Comment by borodust** [comment]
Published [PR](https://github.com/rpav/c2ffi/pull/41) with instructions for similar case.
