### ISSUE TITLE
LLVM 3.8

### ISSUE THREAD

**Issue by ghost** [rpav/c2ffi#34]
`c2ffi` seems to build with LLVM 3.8 (strangely linking code compiled with 3.7 does not quite work). Could you please verify this works and maybe update documentation/CMakeLists.txt.

**Comment by Shinmera** [comment]
Can confirm it building with LLVM38. Unfortunately 37 is no longer available for Arch Linux users, so support for 38 would be great to have.

**Comment by rpav** [comment]
Will update Tuesday unless I get a PR first. ;)

**Comment by stacksmith** [comment]
What is the current status of 3.8?

**Comment by rpav** [comment]
Looking into it now.

**Comment by rpav** [comment]
Ubuntu/Debian 3.8 packages are as usual still completely broken and I don't really have the time to fix all that right now too.  I'll have to look at this when I'm back on something sane.

Probably this will compile if you just change the required version to 3.8... unless you're on Ubuntu or Debian, in which case, back to building LLVM/Clang from source yourself I guess.

**Comment by stacksmith** [comment]
Thanks, I wound up getting ubuntu 3.7 packages and it seems to work.  Although I could not get cl-sdl2 to generate a working autowrap spec for sdl2.0.5...  The whole thing is just a mess.

**Comment by rpav** [comment]
Ah it looks like 2.0.5 is out.  Some of the autowrap/c2ffi stuff may be based on specific system quirks (e.g. where certain include files live) in order to exclude/include certain definitions.

**Comment by stacksmith** [comment]
Indeed, I was hoping it would 'just work' but it will require massaging... More than my limited understanding allows for.
