### ISSUE TITLE
c2ffi doesn't parse #if defined() #else #endif statements correctly

### ISSUE THREAD

**Issue by ychakiris** [rpav/c2ffi#48]
## Background with using cl-autowrap on curl.h

I was working on providing more test cases for cl-autowrap and I was cleaning up the present set of tests. In the process of using libcurl to create another set of tests from wrapping curl.h, I noticed strange thing, probably a bug in c2ffi. Note that I build the libcurl fresh by creating a `t_curl` subdirectory in cl-autowrap and used the appropriate `--use-prefix` to install it in the `t_curl` subdirectory. In general, I think that the tests for cl-autowrap should be done this way so there are no issues with version numbers of the libraries being wrapped. 

I first noticed this from the fact that cl-autowrap would not successfully wrap the libcurl functions like `curl_easy_setopt` or any of the `curl_easy_xxxx` type functions but it successfully wrapped most of the rest of the `curl.h` file. The difference seemed to be the fact that the declaration for `curl_easy_setop` had as its first argument `CURL *handle`. However if I manually changed the curl.h file and included a statement like:
```
#define CURL void
```
Then `curl_easy_setopt` was correctly wrapped. From this I decided to investigate the c2ffi output that feeds into cl-autowrap. In doing so, I found some strange behavior with conditional compile statements. 

## Investigation of applying c2ffi to curl.h

In the file curl.h near the beginning we have the following conditional compile statements:
```
#if defined(BUILDING_LIBCURL) || defined(CURL_STRICTER)
   typedef struct Curl_easy CURL;
   typedef struct Curl_share CURLSH;
#else
  typedef void CURL;
  typedef void CURLSH;
#endif
```
If I run the following command at the CLI:
```
c2ffi curl.h | grep easy
```
Then none of the `curl_easy_xxxx` functions show successful parsing. If I define `CURL` to be `void`, as mentioned in the last section, then they are all correctly parsed. Note that neither `BUILDING_LIBCURL` nor `CURL_STRICT` are defined and so this manual define should not be needed. 

However, and here the plot thickens, if we *repeat* the above code twice in a row, the `curl_easy_xxxx` conditional statements are parsed correctly. Namely if we simply do this in curl.h:

```
#if defined(BUILDING_LIBCURL) || defined(CURL_STRICTER)
   typedef struct Curl_easy CURL;
   typedef struct Curl_share CURLSH;
#else
  typedef void CURL;
  typedef void CURLSH;
#endif

#if defined(BUILDING_LIBCURL) || defined(CURL_STRICTER)
   typedef struct Curl_easy CURL;
   typedef struct Curl_share CURLSH;
#else
  typedef void CURL;
  typedef void CURLSH;
#endif
```
Actually the second repetition can be modified with different types conditional statements and it still works. This means that the parsing is correctly making `CURL` be equivalent to `void` based on the second set of conditional statements but the first set of conditional statements doesn't do that, although it should.

**Comment by rpav** [comment]
`c2ffi` just relies on clang to parse everything, including any preprocessor directives.  I'm not sure why this particular combination causes things to work out---possibly clang encountering the same typedef twice and creates an "invalid" record, and `c2ffi` doesn't check for invalidity.

But the real problem is likely it can't find your `sys/types.h`.  Check the output *with errors* and see if this is an issue near the top of the output:

```console
$ c2ffi /usr/include/curl/curl.h 2>&1 | less -S
[
In file included from /usr/include/curl/curl.h:34:
/usr/include/curl/curlbuild.h:131:12: fatal error: 'sys/types.h' file not found
#  include <sys/types.h>
           ^
...
```

In my case, this caused numerous invalid declarations including the `_easy_` functions.  `c2ffi` can only guess at some default directories, so including the "right" system directory is necessary:

```console
$ c2ffi -i/usr/include/x86_64-linux-gnu /usr/include/curl/curl.h 2>&1 |less -S
...
```

This produces what appears to be correct output on my system (said directory is where `sys/types.h` lives).

**Comment by ychakiris** [comment]
That fixed it!!
