### ISSUE TITLE
nan handling

### ISSUE THREAD

**Issue by Zulu-Inuoe** [rpav/c2ffi#49]
My math.h contains a definition for NAN as follows

#define NAN (0.0f/0.0f)

Which results in c2ffi json output as follows:

{ "tag": "const", "name": "NAN", "ns": 0, "location": "/usr/include/math.h:100:13", "type": { "tag": ":double", "bit-size": 64, "bit-alignment": 64 }, "value": nan }

Unfortunately, the JSON spec doesn't seem have NaN handling, so the above isn't legal JSON, which is making my parser barf.

I haven't a clue as to what the right 'fix' for this is as far as c2ffi is concerned.
No value? Some special sentinel value?

Thanks and thoughts appreciated.

**Comment by rpav** [comment]
I suppose a simple test and output as string would be sufficient here... it should be valid JSON and unambiguous to parsers..

**Comment by Zulu-Inuoe** [comment]
Yes. I just noticed the commit 

30436b8c92e58ec7fa2db8fc3742d702d2b99888

where the same situation is handled for 'inf'.

Apologies. Should have though to look at inf handling first.

**Comment by rpav** [comment]
I didn't even recall... I should have handled NaN at the same time.
