### ISSUE TITLE
llvm 5.0?

### ISSUE THREAD

**Issue by anticrisis** [rpav/c2ffi#55]
Any plans to make this extremely useful tool build with clang/llvm 5.0? I ask because the 4.0 version currently required by this project is not easily installable on ArchLinux for reasons I don't understand. (It used to be available, but now only 5.0 and 3.9 and lower are available.) 

https://www.archlinux.org/packages/?sort=&arch=x86_64&q=llvm

**Comment by rpav** [comment]
Yeah I just need to get 5.0 built... since I'm actually thinking of it I'll kick it off now and then with any luck the c2ffi updates shouldn't be too huge.

**Comment by rpav** [comment]
The `llvm-5.0.0` branch is now available.  Let me know if you have issues.
