### ISSUE TITLE
make install does nothing

### ISSUE THREAD

**Issue by VanLaser** [rpav/c2ffi#60]
Hi, I made a c2ffi AUR [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=c2ffi-git) recipe for Arch Linux ([link](https://aur.archlinux.org/packages/c2ffi-git/)) and I had to install the binary "manually" (so to speak) to `/usr/bin` because, following the building instructions here, doing a `make install` does ... nothing. Is there anything I missed, or is `make install` currently a noop? (BTW, I'm not good at `cmake` stuff, otherwise I would have patched the relevant file(s) already).

**Comment by rpav** [comment]
Err it should but I might not have set that up.  I don't use the cmake install stuff enough or I'd just post the directive.  Will fix tomorrow.

**Comment by rpav** [comment]
Looks like when I cleaned up CMakeLists.txt, I missed the variable in `install`.  Should be fixed.

**Comment by VanLaser** [comment]
Thanks a lot!
