### ISSUE TITLE
CommandLine Error: Option 'disable-symbolication' registered more than once!

### ISSUE THREAD

**Issue by andreadipersio** [rpav/c2ffi#63]
Hello,
after successfully building on LLVM 8 (on Fedora 30), running `c2ffi` fails with:

```
: CommandLine Error: Option 'disable-symbolication' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

Searching for clues I stumbled upon this comment: https://github.com/ziglang/zig/issues/67#issuecomment-482909287

The solution seems to fix the problem on my machine.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 72a224a..b2bd75e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -68,7 +68,7 @@ target_link_libraries(c2ffi PUBLIC
   clangIndex
   clangToolingCore
   clangTooling
-  ${llvm_libs})
+  LLVM)
 
 set(APP_BIN_DIR "${CMAKE_BINARY_DIR}/bin")
 set_target_properties(c2ffi PROPERTIES
```

**Comment by rpav** [comment]
Err .. late, but this ought to be fixed with the update to CMakeLists.txt. `llvm_config` should hopefully pick the right thing, though I haven't tested it on static configurations.

**Comment by rpav** [comment]
This ought to be fixed.
