### ISSUE TITLE
ld: library not found for -lclangFrontendTool

### ISSUE THREAD

**Issue by shenxs** [rpav/c2ffi#64]
get an error while make:
```
ld: library not found for -lclangFrontendTool
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/c2ffi] Error 1
make[1]: *** [CMakeFiles/c2ffi.dir/all] Error 2
make: *** [all] Error 2
```
solved by add the following to CMakeLists.txt:

```
target_link_directories(
  c2ffi PUBLIC
  /usr/local/Cellar/llvm/8.0.1/lib/
  ) 
```
the path maybe different on your system

My Environment：
- Mac OSX  10.14.6
- llvm 8.0.1  (installed with `brew install llvm`)

Hope that would be helpful to those who come across  the same issue

**Comment by vuolen** [comment]
I had this same issue, but afaik cmake 10 (the version i have) does not have target_link_directories. I had to implement it like this for every library:

```
find_library(CLANGFRONTENDTOOL-LIB
  clangFrontendTool
  PATHS ${LLVM_LIBRARY_DIRS}
  )

...

target_link_libraries(c2ffi PUBLIC
  ${CLANGFRONTENDTOOL-LIB}
  ...
  )
```

You could probably achieve this more elegantly but this was the easiest fix for me at the moment.

All in all, the project should search `LLVM_LIBRARY_DIRS` for libraries. And in a way that is compatible with older cmake versions. `CMakeLists.txt` has a minimum version of 3.8

**Comment by rpav** [comment]
This *should* not be an issue with the new `llvm_config` setup... is this still an issue for someone?

**Comment by shenxs** [comment]
> This _should_ not be an issue with the new `llvm_config` setup... is this still an issue for someone?

it still the same issue on Mac。

**Comment by rpav** [comment]
Oh right, this is almost certainly a bug with brew packaging of the library.

**Comment by ngocdaothanh** [comment]
> certainly a bug with brew packaging of the library

I'm using Mac and I have this `library not found for -lclangFrontendTool` problem too.

I'm not using CLang and LLVM from brew:

* CMake: 3.15.5, installed by brew
* Clang and LLVM: 9.0.0, pre-built binary downloaded from http://releases.llvm.org/download.html

I see that `lib/cmake/llvm/LLVMConfig.cmake` is included by c2ffi's config. Maybe it should also include `lib/cmake/clang/ClangConfig.cmake`?

**Comment by ngocdaothanh** [comment]
I've created a PR to fix:
https://github.com/rpav/c2ffi/pull/68/files

**Comment by rpav** [comment]
Please reopen if this is still an issue.
