### ISSUE TITLE
llvm-9.0.0 branch does not build on gentoo

### ISSUE THREAD

**Issue by hjudt** [rpav/c2ffi#71]
The llvm-9.0.0 branch did not build on gentoo. I have fixed it and sent a pull request #70.

**Comment by ngocdaothanh** [comment]
I created similar PR 3 days ago:
https://github.com/rpav/c2ffi/pull/68/files

Maybe the maintainers of this project are on holiday?

CC @rpav

**Comment by rpav** [comment]
(This doesn't seem relevant any longer, and the patch appears to have a number of issues and would need to be verified on other platforms .. but 9.x stuff isn't really supported now.  If this is still desired/required, feel free to reopen.  Apologies for not getting to this when it mattered.)
