### ISSUE TITLE
Build fail with ubuntu

### ISSUE THREAD

**Issue by dangquan-quoine** [rpav/c2ffi#75]
Hi rpav
I have an error wheen i build on ubuntu. it may be not found some lib of clang. could you help me, thanks! @rpav 
<img width="573" alt="Screen Shot 2020-11-09 at 17 28 00" src="https://user-images.githubusercontent.com/50191846/98530164-23328000-22b1-11eb-8c6c-f12a1499445a.png">

**Comment by rpav** [comment]
Pasting screenshots is not nearly as helpful as a gist with a full log .. what branch of c2ffi are you using? What clang/llvm packages do you have installed?

**Comment by dangquan-quoine** [comment]
Yes, I installed  llvm v9 with apt-get install. i use clang v10 with the same install (apt-get install). the branch: llvm-9.0.0

**Comment by rpav** [comment]
I'm taking the above to mean your checked-out c2ffi branch and llvm/clang versions all match.

But you almost certainly need `llvm-dev` / `clang-dev` packages.  Missing headers is a big indication.  Ubuntu packages have often been incomplete/broken here though, not including everything necessary.  If installing these fails, you may need to build clang/llvm yourself.

**Comment by dangquan-quoine** [comment]
thanks for your supporting, it is missing some dev package when i use  apt-get install, i will try your solution. Could you recommend your environment linux which you can build success easy?

**Comment by rpav** [comment]
I'm not sure I've had a lot of trouble building in any dist, just using dist-provided (even official, llvm.org) packages. Fwiw arch linux packages seem to have everything and build c2ffi without issue.  But you can build llvm/clang in an hour or so anywhere i think.

**Comment by dangquan-quoine** [comment]
thanks for your supporting. I have solved my  problem. when i use apt-get install, it not download dev packages. i must install dev package for import header file.
