### ISSUE TITLE
CMake: BUILD_CONFIG not recognized: ''

### ISSUE THREAD

**Issue by piknik** [rpav/c2ffi#84]
I've ran into a minor issue while following the building guide.

When running `cmake ..` I get the following:
```
CMake Error at CMake/setup.cmake:47 (message):
  BUILD_CONFIG not recognized: ''
Call Stack (most recent call first):
  CMakeLists.txt:3 (include)


-- Configuring incomplete, errors occurred!
```
But after specifying the BUILD_CONFIG variable with `cmake -DBUILD_CONFIG=Release .` it works fine and I am able to complete the build process.

`cmake --version`:
```
cmake version 3.19.3
```

I'm not sure whether my system is misconfigured or if CMake changed its behavior from something the building guide expects.

EDIT: This would be on the current branch (llvm-11.0.0)

**Comment by rpav** [comment]
Argh, this should default, but amidst all the automation testing I didn't build manually!  Workaround until I get back to this is `cmake -DBUILD_CONFIG=Release ...` (or Debug, Sanitize...).
