### ISSUE TITLE
Nix(OS) build integration?

### ISSUE THREAD

**Issue by attila-lendvai** [rpav/c2ffi#93]
are you interested in a `default.nix` file?

it enables anyone who has Nix installed to type `nix-shell` in the project directory to enter an environment that contains all the required dependencies (everything is automatically downloaded, and held temporarily "installed" in that shell).

if you are interested i can finish it up and open a PR, but i want to spare the trouble if you don't want that in the repo.

**Comment by rpav** [comment]
Sure! I don't really have the facilities on hand to test it at the moment, but feel free to add some CI configuration or similar to keep it checked as well.

I'm pretty happy to add anything that makes it more accessible.

**Comment by attila-lendvai** [comment]
implemented in https://github.com/rpav/c2ffi/pull/96
